default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_NAME"] %>
  username: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_USERNAME"] %>
  password: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PASSWORD"] %>
  host: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_HOST"] %>

test:
  <<: *default
  username: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_USERNAME"] %>
  password: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PASSWORD"] %>
  database: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_TEST_NAME"] %>
  host: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_HOST"] %>

production:
  <<: *default
  database: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PRODUCTION_NAME"] %>
  username: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PRODUCTION_USERNAME"] %>
  password: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PRODUCTION_PASSWORD"] %>
  host: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PRODUCTION_HOST"] %>
  port: 5432
