default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_NAME"] %>
  username: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_USERNAME"] %>
  password: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PASSWORD"] %>
  host: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_HOST"] %>

test:
  <<: *default
  username: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_USERNAME"] %>
  password: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PASSWORD"] %>
  database: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_TEST_NAME"] %>
  host: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_HOST"] %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PRODUCTION_NAME"] %>
    username: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PRODUCTION_USERNAME"] %>
    password: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PRODUCTION_PASSWORD"] %>
    host: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_PRODUCTION_HOST"] %>
    port: 5432
  cache:
    <<: *primary_production
    database: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_CACHE_PRODUCTION_NAME"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_QUEUE_PRODUCTION_NAME"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV["MY_SLEEP_JOURNEY_DATABASE_CABLE_PRODUCTION_NAME"] %>
    migrations_paths: db/cable_migrate
